//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViewResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acoustic.
        /// </summary>
        public static string Acoustic {
            get {
                return ResourceManager.GetString("Acoustic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acoustics.
        /// </summary>
        public static string Acoustics {
            get {
                return ResourceManager.GetString("Acoustics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Rw(C, Ctr)/STC/OITC values and sound transmission loss in 100-5000Hz for complex windows and façades..
        /// </summary>
        public static string AcousticsInfo {
            get {
                return ResourceManager.GetString("AcousticsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In accordance with DIN 4109-2:2018 &quot;Sound insulation in buildings - Part 2: Verification of compliance with the requirements by calculation&quot;, an area-based energy calculation of the “weighted sound reduction index of building components” Rw,res has been carried out for the user-defined window unit..
        /// </summary>
        public static string AcousticsInfoText {
            get {
                return ResourceManager.GetString("AcousticsInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        public static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add notes.
        /// </summary>
        public static string AddNotes {
            get {
                return ResourceManager.GetString("AddNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air.
        /// </summary>
        public static string Air {
            get {
                return ResourceManager.GetString("Air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airport.
        /// </summary>
        public static string Airport {
            get {
                return ResourceManager.GetString("Airport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airspace.
        /// </summary>
        public static string Airspace {
            get {
                return ResourceManager.GetString("Airspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alloys.
        /// </summary>
        public static string Alloys {
            get {
                return ResourceManager.GetString("Alloys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aluminum.
        /// </summary>
        public static string Aluminum {
            get {
                return ResourceManager.GetString("Aluminum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aluminum Stress.
        /// </summary>
        public static string AluminumStress {
            get {
                return ResourceManager.GetString("AluminumStress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argon Air.
        /// </summary>
        public static string ArgonAir {
            get {
                return ResourceManager.GetString("ArgonAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article number.
        /// </summary>
        public static string ArticleNumber {
            get {
                return ResourceManager.GetString("ArticleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average U-Value.
        /// </summary>
        public static string AverageUValue {
            get {
                return ResourceManager.GetString("AverageUValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axes.
        /// </summary>
        public static string Axes {
            get {
                return ResourceManager.GetString("Axes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axial Force.
        /// </summary>
        public static string AxialForce {
            get {
                return ResourceManager.GetString("AxialForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom-Hung.
        /// </summary>
        public static string BottomHung {
            get {
                return ResourceManager.GetString("BottomHung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boundary Condition.
        /// </summary>
        public static string BoundaryCondition {
            get {
                return ResourceManager.GetString("BoundaryCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to building depth.
        /// </summary>
        public static string BuildingDepth {
            get {
                return ResourceManager.GetString("BuildingDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to building height.
        /// </summary>
        public static string BuildingHeight {
            get {
                return ResourceManager.GetString("BuildingHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building information.
        /// </summary>
        public static string BuildingInformation {
            get {
                return ResourceManager.GetString("BuildingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building width.
        /// </summary>
        public static string BuildingWidth {
            get {
                return ResourceManager.GetString("BuildingWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate wind load.
        /// </summary>
        public static string CalculateWindLoad {
            get {
                return ResourceManager.GetString("CalculateWindLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Wind Pressure.
        /// </summary>
        public static string CalculateWindPressure {
            get {
                return ResourceManager.GetString("CalculateWindPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center of Glass U-Value.
        /// </summary>
        public static string CenterOfGlassUValue {
            get {
                return ResourceManager.GetString("CenterOfGlassUValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        public static string Chart {
            get {
                return ResourceManager.GetString("Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to upload.
        /// </summary>
        public static string ClickToUpload {
            get {
                return ResourceManager.GetString("ClickToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute.
        /// </summary>
        public static string Compute {
            get {
                return ResourceManager.GetString("Compute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Panel.
        /// </summary>
        public static string ConfigurationPanel {
            get {
                return ResourceManager.GetString("ConfigurationPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        public static string Configure {
            get {
                return ResourceManager.GetString("Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact support.
        /// </summary>
        public static string ContactSupport {
            get {
                return ResourceManager.GetString("ContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new glass configuration.
        /// </summary>
        public static string CreateNewGlassConfig {
            get {
                return ResourceManager.GetString("CreateNewGlassConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom profile.
        /// </summary>
        public static string CustomProfile {
            get {
                return ResourceManager.GetString("CustomProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dead load.
        /// </summary>
        public static string DeadLoad {
            get {
                return ResourceManager.GetString("DeadLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsche Flagge.
        /// </summary>
        public static string DEFlag {
            get {
                return ResourceManager.GetString("DEFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deflection.
        /// </summary>
        public static string Deflection {
            get {
                return ResourceManager.GetString("Deflection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deflection criteria.
        /// </summary>
        public static string DeflectionCriteria {
            get {
                return ResourceManager.GetString("DeflectionCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting intermediates will remove panes you have added to your glass configurations. Do you want to continue?.
        /// </summary>
        public static string DeleteIntermediatePaneWarning {
            get {
                return ResourceManager.GetString("DeleteIntermediatePaneWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dew Point Calculator.
        /// </summary>
        public static string DewPointCalculator {
            get {
                return ResourceManager.GetString("DewPointCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dew point T Calculator.
        /// </summary>
        public static string DewPointTCalculator {
            get {
                return ResourceManager.GetString("DewPointTCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension.
        /// </summary>
        public static string Dimension {
            get {
                return ResourceManager.GetString("Dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These programs are used for the approximate determination of technical parameters. The results of these pre-dimensioning do not replace the required detailed planning and do not constitute proof of compliance with building regulations. The exclusive rights of use are owned by Schüco International KG..
        /// </summary>
        public static string DisclaimerText {
            get {
                return ResourceManager.GetString("DisclaimerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door.
        /// </summary>
        public static string Door {
            get {
                return ResourceManager.GetString("Door", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Glass Library.
        /// </summary>
        public static string DoubleGlassLibrary {
            get {
                return ResourceManager.GetString("DoubleGlassLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Vent (SH/SH).
        /// </summary>
        public static string DoubleVentShSh {
            get {
                return ResourceManager.GetString("DoubleVentShSh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Vent (SH/TT).
        /// </summary>
        public static string DoubleVentShTt {
            get {
                return ResourceManager.GetString("DoubleVentShTt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download in one pdf.
        /// </summary>
        public static string DownloadInOnePdf {
            get {
                return ResourceManager.GetString("DownloadInOnePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag.
        /// </summary>
        public static string Drag {
            get {
                return ResourceManager.GetString("Drag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag OR Click to upload.
        /// </summary>
        public static string DragORClickToUpload {
            get {
                return ResourceManager.GetString("DragORClickToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string E_mail {
            get {
                return ResourceManager.GetString("E_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge.
        /// </summary>
        public static string Edge {
            get {
                return ResourceManager.GetString("Edge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge zone.
        /// </summary>
        public static string EdgeZone {
            get {
                return ResourceManager.GetString("EdgeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environmental Audio.
        /// </summary>
        public static string EnvironmentalAudio {
            get {
                return ResourceManager.GetString("EnvironmentalAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expansion profile.
        /// </summary>
        public static string ExpansionProfile {
            get {
                return ResourceManager.GetString("ExpansionProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure Category.
        /// </summary>
        public static string ExposureCategory {
            get {
                return ResourceManager.GetString("ExposureCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facade.
        /// </summary>
        public static string Facade {
            get {
                return ResourceManager.GetString("Facade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Façade.
        /// </summary>
        public static string Façade {
            get {
                return ResourceManager.GetString("Façade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire truck.
        /// </summary>
        public static string FireTruck {
            get {
                return ResourceManager.GetString("FireTruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        public static string Fixed {
            get {
                return ResourceManager.GetString("Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed / opening.
        /// </summary>
        public static string FixedOrOpening {
            get {
                return ResourceManager.GetString("FixedOrOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your username or password?.
        /// </summary>
        public static string ForgotUsernamePassword {
            get {
                return ResourceManager.GetString("ForgotUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame.
        /// </summary>
        public static string Frame {
            get {
                return ResourceManager.GetString("Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame area.
        /// </summary>
        public static string FrameArea {
            get {
                return ResourceManager.GetString("FrameArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framing.
        /// </summary>
        public static string Framing {
            get {
                return ResourceManager.GetString("Framing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain.
        /// </summary>
        public static string Gain {
            get {
                return ResourceManager.GetString("Gain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaskets.
        /// </summary>
        public static string Gaskets {
            get {
                return ResourceManager.GetString("Gaskets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaskets with fins.
        /// </summary>
        public static string GasketsWithFins {
            get {
                return ResourceManager.GetString("GasketsWithFins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Aluminum.
        /// </summary>
        public static string GeneralAluminumSpacer {
            get {
                return ResourceManager.GetString("GeneralAluminumSpacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Non-Stainless Steel.
        /// </summary>
        public static string GeneralNonStainlessSteelSpacer {
            get {
                return ResourceManager.GetString("GeneralNonStainlessSteelSpacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Thermally Improved.
        /// </summary>
        public static string GeneralThermallyImprovedSpacer {
            get {
                return ResourceManager.GetString("GeneralThermallyImprovedSpacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass.
        /// </summary>
        public static string Glass {
            get {
                return ResourceManager.GetString("Glass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass Edge Seal.
        /// </summary>
        public static string Glass_Edge_Seal {
            get {
                return ResourceManager.GetString("Glass Edge Seal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass &amp; Panel.
        /// </summary>
        public static string GlassAndPanel {
            get {
                return ResourceManager.GetString("GlassAndPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass &amp; Spandrel.
        /// </summary>
        public static string GlassAndSpandrel {
            get {
                return ResourceManager.GetString("GlassAndSpandrel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass area.
        /// </summary>
        public static string GlassArea {
            get {
                return ResourceManager.GetString("GlassArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass Description.
        /// </summary>
        public static string GlassDescription {
            get {
                return ResourceManager.GetString("GlassDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass edge seal.
        /// </summary>
        public static string GlassEdgeSeal {
            get {
                return ResourceManager.GetString("GlassEdgeSeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass Info.
        /// </summary>
        public static string GlassInfo {
            get {
                return ResourceManager.GetString("GlassInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass RW.
        /// </summary>
        public static string GlassRW {
            get {
                return ResourceManager.GetString("GlassRW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glazing gasket combination.
        /// </summary>
        public static string GlazingGasketCombination {
            get {
                return ResourceManager.GetString("GlazingGasketCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option 1.
        /// </summary>
        public static string GlazingGasketCombinationOption1 {
            get {
                return ResourceManager.GetString("GlazingGasketCombinationOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with glazing rebate insulation, assembly insulation first.
        /// </summary>
        public static string GlazingGasketCombinationOption1Content {
            get {
                return ResourceManager.GetString("GlazingGasketCombinationOption1Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option 2.
        /// </summary>
        public static string GlazingGasketCombinationOption2 {
            get {
                return ResourceManager.GetString("GlazingGasketCombinationOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with glazing rebate insulation, assembly glazing first,288138, 288149.
        /// </summary>
        public static string GlazingGasketCombinationOption2Content {
            get {
                return ResourceManager.GetString("GlazingGasketCombinationOption2Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option 3.
        /// </summary>
        public static string GlazingGasketCombinationOption3 {
            get {
                return ResourceManager.GetString("GlazingGasketCombinationOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with gasket fin.
        /// </summary>
        public static string GlazingGasketCombinationOption3Content {
            get {
                return ResourceManager.GetString("GlazingGasketCombinationOption3Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option 4.
        /// </summary>
        public static string GlazingGasketCombinationOption4 {
            get {
                return ResourceManager.GetString("GlazingGasketCombinationOption4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to without glazing rebate insulation.
        /// </summary>
        public static string GlazingGasketCombinationOption4Content {
            get {
                return ResourceManager.GetString("GlazingGasketCombinationOption4Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glazing Rebate Insulation.
        /// </summary>
        public static string GlazingRebateInsulation {
            get {
                return ResourceManager.GetString("GlazingRebateInsulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid.
        /// </summary>
        public static string Grid {
            get {
                return ResourceManager.GetString("Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guidance.
        /// </summary>
        public static string Guidance {
            get {
                return ResourceManager.GetString("Guidance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help &amp; Support.
        /// </summary>
        public static string HelpAndSupport {
            get {
                return ResourceManager.GetString("HelpAndSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imperial.
        /// </summary>
        public static string Imperial {
            get {
                return ResourceManager.GetString("Imperial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info Panel.
        /// </summary>
        public static string InfoPanel {
            get {
                return ResourceManager.GetString("InfoPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inside.
        /// </summary>
        public static string Inside {
            get {
                return ResourceManager.GetString("Inside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insulating Bar.
        /// </summary>
        public static string InsulatingBar {
            get {
                return ResourceManager.GetString("InsulatingBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlike the setting in the fabrication data block, polyamide insulating bars are calculated..
        /// </summary>
        public static string InsulatingBarText {
            get {
                return ResourceManager.GetString("InsulatingBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insulation.
        /// </summary>
        public static string Insulation {
            get {
                return ResourceManager.GetString("Insulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inward.
        /// </summary>
        public static string Inward {
            get {
                return ResourceManager.GetString("Inward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Ratios.
        /// </summary>
        public static string KeyRatios {
            get {
                return ResourceManager.GetString("KeyRatios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laminate.
        /// </summary>
        public static string Laminate {
            get {
                return ResourceManager.GetString("Laminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laminated Glass.
        /// </summary>
        public static string LaminatedGlass {
            get {
                return ResourceManager.GetString("LaminatedGlass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal.
        /// </summary>
        public static string Legal {
            get {
                return ResourceManager.GetString("Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightweight Hollow CMU.
        /// </summary>
        public static string LightweightHollowCMU {
            get {
                return ResourceManager.GetString("LightweightHollowCMU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Type.
        /// </summary>
        public static string LoadType {
            get {
                return ResourceManager.GetString("LoadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Log_in {
            get {
                return ResourceManager.GetString("Log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Absolute Value.
        /// </summary>
        public static string MaxAbsoluteValue {
            get {
                return ResourceManager.GetString("MaxAbsoluteValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string Maximum {
            get {
                return ResourceManager.GetString("Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric.
        /// </summary>
        public static string Metric {
            get {
                return ResourceManager.GetString("Metric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Zone.
        /// </summary>
        public static string MiddleZone {
            get {
                return ResourceManager.GetString("MiddleZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moment.
        /// </summary>
        public static string Moment {
            get {
                return ResourceManager.GetString("Moment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mullion / Transom.
        /// </summary>
        public static string MullionOrTransom {
            get {
                return ResourceManager.GetString("MullionOrTransom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mullion / Transom Library.
        /// </summary>
        public static string MullionOrTransomLibrary {
            get {
                return ResourceManager.GetString("MullionOrTransomLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative Wind load.
        /// </summary>
        public static string NegativeWindLoad {
            get {
                return ResourceManager.GetString("NegativeWindLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project.
        /// </summary>
        public static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Day ago.
        /// </summary>
        public static string OneDayAgo {
            get {
                return ResourceManager.GetString("OneDayAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 month ago.
        /// </summary>
        public static string OneMonthAgo {
            get {
                return ResourceManager.GetString("OneMonthAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening.
        /// </summary>
        public static string Opening {
            get {
                return ResourceManager.GetString("Opening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Percentage.
        /// </summary>
        public static string OpeningPercentage {
            get {
                return ResourceManager.GetString("OpeningPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operability.
        /// </summary>
        public static string Operability {
            get {
                return ResourceManager.GetString("Operability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operable.
        /// </summary>
        public static string Operable {
            get {
                return ResourceManager.GetString("Operable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperableType.
        /// </summary>
        public static string OperableType {
            get {
                return ResourceManager.GetString("OperableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to option.
        /// </summary>
        public static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outer Frame.
        /// </summary>
        public static string OuterFrame {
            get {
                return ResourceManager.GetString("OuterFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outer Frame Library.
        /// </summary>
        public static string OuterFrameLibrary {
            get {
                return ResourceManager.GetString("OuterFrameLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outside.
        /// </summary>
        public static string Outside {
            get {
                return ResourceManager.GetString("Outside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outward.
        /// </summary>
        public static string Outward {
            get {
                return ResourceManager.GetString("Outward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall performance.
        /// </summary>
        public static string OverallPerformance {
            get {
                return ResourceManager.GetString("OverallPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Window.
        /// </summary>
        public static string OverallWindow {
            get {
                return ResourceManager.GetString("OverallWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall window performance.
        /// </summary>
        public static string OverallWindowPerformance {
            get {
                return ResourceManager.GetString("OverallWindowPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall window performance (dB).
        /// </summary>
        public static string OverallWindowPerformanceDB {
            get {
                return ResourceManager.GetString("OverallWindowPerformanceDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel.
        /// </summary>
        public static string Panel {
            get {
                return ResourceManager.GetString("Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel Library.
        /// </summary>
        public static string PanelLibrary {
            get {
                return ResourceManager.GetString("PanelLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panels.
        /// </summary>
        public static string Panels {
            get {
                return ResourceManager.GetString("Panels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissible Deflection.
        /// </summary>
        public static string PermissibleDeflection {
            get {
                return ResourceManager.GetString("PermissibleDeflection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physics Type.
        /// </summary>
        public static string PhysicsType {
            get {
                return ResourceManager.GetString("PhysicsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyamide.
        /// </summary>
        public static string Polyamide {
            get {
                return ResourceManager.GetString("Polyamide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (PA) Anodized After.
        /// </summary>
        public static string PolyamideAnodizedAfter {
            get {
                return ResourceManager.GetString("PolyamideAnodizedAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (PA) Anodized Before.
        /// </summary>
        public static string PolyamideAnodizedBefore {
            get {
                return ResourceManager.GetString("PolyamideAnodizedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (PA) Coated After.
        /// </summary>
        public static string PolyamideCoatedAfter {
            get {
                return ResourceManager.GetString("PolyamideCoatedAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (PA) Coated Before.
        /// </summary>
        public static string PolyamideCoatedBefore {
            get {
                return ResourceManager.GetString("PolyamideCoatedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polythermid.
        /// </summary>
        public static string Polythermid {
            get {
                return ResourceManager.GetString("Polythermid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (PT) Anodized Before.
        /// </summary>
        public static string PolythermidAnodizedBefore {
            get {
                return ResourceManager.GetString("PolythermidAnodizedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (PT) Coated Before.
        /// </summary>
        public static string PolythermidCoatedBefore {
            get {
                return ResourceManager.GetString("PolythermidCoatedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive Wind load.
        /// </summary>
        public static string PositiveWindLoad {
            get {
                return ResourceManager.GetString("PositiveWindLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POWERED BY.
        /// </summary>
        public static string PoweredBy {
            get {
                return ResourceManager.GetString("PoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preliminary.
        /// </summary>
        public static string Preliminary {
            get {
                return ResourceManager.GetString("Preliminary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Info.
        /// </summary>
        public static string ProductInfo {
            get {
                return ResourceManager.GetString("ProductInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type.
        /// </summary>
        public static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile ID name.
        /// </summary>
        public static string ProfileIDName {
            get {
                return ResourceManager.GetString("ProfileIDName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name.
        /// </summary>
        public static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project location.
        /// </summary>
        public static string ProjectLocation {
            get {
                return ResourceManager.GetString("ProjectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project properties.
        /// </summary>
        public static string ProjectProperties {
            get {
                return ResourceManager.GetString("ProjectProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psi-Value.
        /// </summary>
        public static string PsiValue {
            get {
                return ResourceManager.GetString("PsiValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactions.
        /// </summary>
        public static string Reactions {
            get {
                return ResourceManager.GetString("Reactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular gaskets.
        /// </summary>
        public static string RegularGaskets {
            get {
                return ResourceManager.GetString("RegularGaskets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative humidity.
        /// </summary>
        public static string RelativeHumidity {
            get {
                return ResourceManager.GetString("RelativeHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype Email.
        /// </summary>
        public static string RetypeEmail {
            get {
                return ResourceManager.GetString("RetypeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype Password.
        /// </summary>
        public static string RetypePassword {
            get {
                return ResourceManager.GetString("RetypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk category of building.
        /// </summary>
        public static string RiskCategoryOfBuilding {
            get {
                return ResourceManager.GetString("RiskCategoryOfBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Area.
        /// </summary>
        public static string RoomArea {
            get {
                return ResourceManager.GetString("RoomArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by article number.
        /// </summary>
        public static string SearchByArticleNumber {
            get {
                return ResourceManager.GetString("SearchByArticleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by dimension.
        /// </summary>
        public static string SearchByDimension {
            get {
                return ResourceManager.GetString("SearchByDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Properties.
        /// </summary>
        public static string SectionProperties {
            get {
                return ResourceManager.GetString("SectionProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        public static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shear Force.
        /// </summary>
        public static string ShearForce {
            get {
                return ResourceManager.GetString("ShearForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side-Hung.
        /// </summary>
        public static string SideHung {
            get {
                return ResourceManager.GetString("SideHung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        public static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Wood Stud.
        /// </summary>
        public static string SingleWoodStud {
            get {
                return ResourceManager.GetString("SingleWoodStud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site information.
        /// </summary>
        public static string SiteInformation {
            get {
                return ResourceManager.GetString("SiteInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sliding Door.
        /// </summary>
        public static string SlidingDoor {
            get {
                return ResourceManager.GetString("SlidingDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid Concrete Panel.
        /// </summary>
        public static string SolidConcretePanel {
            get {
                return ResourceManager.GetString("SolidConcretePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Transmission Loss (dB).
        /// </summary>
        public static string SoundTransmissionLossDB {
            get {
                return ResourceManager.GetString("SoundTransmissionLossDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacer.
        /// </summary>
        public static string Spacer {
            get {
                return ResourceManager.GetString("Spacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacer Type.
        /// </summary>
        public static string SpacerType {
            get {
                return ResourceManager.GetString("SpacerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stainless Steel.
        /// </summary>
        public static string StainlessSteel {
            get {
                return ResourceManager.GetString("StainlessSteel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stick System.
        /// </summary>
        public static string StickSystem {
            get {
                return ResourceManager.GetString("StickSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        public static string Storage {
            get {
                return ResourceManager.GetString("Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structural.
        /// </summary>
        public static string Structural {
            get {
                return ResourceManager.GetString("Structural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficient and reliable structural analysis of windows, doors and façades, supporting both European and US codes..
        /// </summary>
        public static string StructuralInfo {
            get {
                return ResourceManager.GetString("StructuralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Name.
        /// </summary>
        public static string SystemName {
            get {
                return ResourceManager.GetString("SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To access the Building Physics Test Server, log in and accept the terms of use..
        /// </summary>
        public static string TermsOfUse {
            get {
                return ResourceManager.GetString("TermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain category.
        /// </summary>
        public static string TerrainCategory {
            get {
                return ResourceManager.GetString("TerrainCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain category I.
        /// </summary>
        public static string TerrainCategoryI {
            get {
                return ResourceManager.GetString("TerrainCategoryI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open sea; lakes with a free surface of at least 5 km in wind direction; level, flat country without obstacles..
        /// </summary>
        public static string TerrainCategoryI_Info {
            get {
                return ResourceManager.GetString("TerrainCategoryI_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain category II.
        /// </summary>
        public static string TerrainCategoryII {
            get {
                return ResourceManager.GetString("TerrainCategoryII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain with hedges, isolated farm steads, houses or trees, e. g. agricultural areas..
        /// </summary>
        public static string TerrainCategoryII_Info {
            get {
                return ResourceManager.GetString("TerrainCategoryII_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain category III.
        /// </summary>
        public static string TerrainCategoryIII {
            get {
                return ResourceManager.GetString("TerrainCategoryIII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suburbs, industrial or commercial areas; forests/woods.
        /// </summary>
        public static string TerrainCategoryIII_Info {
            get {
                return ResourceManager.GetString("TerrainCategoryIII_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain category IV.
        /// </summary>
        public static string TerrainCategoryIV {
            get {
                return ResourceManager.GetString("TerrainCategoryIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urban areas in which at least 15% of the surface is covered with buildings of a mean height of more than 15 m..
        /// </summary>
        public static string TerrainCategoryIV_Info {
            get {
                return ResourceManager.GetString("TerrainCategoryIV_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain category V.
        /// </summary>
        public static string TerrainCategoryV {
            get {
                return ResourceManager.GetString("TerrainCategoryV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inland regions, mixed profile of type II and Type III..
        /// </summary>
        public static string TerrainCategoryV_Info {
            get {
                return ResourceManager.GetString("TerrainCategoryV_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain category VI.
        /// </summary>
        public static string TerrainCategoryVI {
            get {
                return ResourceManager.GetString("TerrainCategoryVI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coastal areas, mixed profile of type I and Type II..
        /// </summary>
        public static string TerrainCategoryVI_Info {
            get {
                return ResourceManager.GetString("TerrainCategoryVI_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermal.
        /// </summary>
        public static string Thermal {
            get {
                return ResourceManager.GetString("Thermal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermal Break Shear Stress.
        /// </summary>
        public static string ThermalBreakShearStress {
            get {
                return ResourceManager.GetString("ThermalBreakShearStress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U-values for aluminum windows and façades, supporting both European and US codes..
        /// </summary>
        public static string ThermalInfo {
            get {
                return ResourceManager.GetString("ThermalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilt/Turn.
        /// </summary>
        public static string TiltOrTurn {
            get {
                return ResourceManager.GetString("TiltOrTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read and accept the .
        /// </summary>
        public static string TnC1 {
            get {
                return ResourceManager.GetString("TnC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to terms and conditions.
        /// </summary>
        public static string TnC2 {
            get {
                return ResourceManager.GetString("TnC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  of use..
        /// </summary>
        public static string TnC3 {
            get {
                return ResourceManager.GetString("TnC3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torsion.
        /// </summary>
        public static string Torsion {
            get {
                return ResourceManager.GetString("Torsion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total area.
        /// </summary>
        public static string TotalArea {
            get {
                return ResourceManager.GetString("TotalArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train.
        /// </summary>
        public static string Train {
            get {
                return ResourceManager.GetString("Train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triple Glass Library.
        /// </summary>
        public static string TripleGlassLibrary {
            get {
                return ResourceManager.GetString("TripleGlassLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Days ago.
        /// </summary>
        public static string TwoDaysAgo {
            get {
                return ResourceManager.GetString("TwoDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 months ago.
        /// </summary>
        public static string TwoMonthsAgo {
            get {
                return ResourceManager.GetString("TwoMonthsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &amp; Thickness.
        /// </summary>
        public static string TypeAndThickness {
            get {
                return ResourceManager.GetString("TypeAndThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unitized.
        /// </summary>
        public static string Unitized {
            get {
                return ResourceManager.GetString("Unitized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        public static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload DXF.
        /// </summary>
        public static string UploadDXF {
            get {
                return ResourceManager.GetString("UploadDXF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file.
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American Flag.
        /// </summary>
        public static string USAFlag {
            get {
                return ResourceManager.GetString("USAFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Define.
        /// </summary>
        public static string UserDefine {
            get {
                return ResourceManager.GetString("UserDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U-Value.
        /// </summary>
        public static string UValue {
            get {
                return ResourceManager.GetString("UValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To calculate the U value for window and door systems with bonded infill, the Uf value is calculated in relation to the system, with the addition of 0.1 to 0.6 W/(m2K)..
        /// </summary>
        public static string UValueText {
            get {
                return ResourceManager.GetString("UValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vent Frame.
        /// </summary>
        public static string VentFrame {
            get {
                return ResourceManager.GetString("VentFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vent Frame Library.
        /// </summary>
        public static string VentFrameLibrary {
            get {
                return ResourceManager.GetString("VentFrameLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vent Profile.
        /// </summary>
        public static string VentProfile {
            get {
                return ResourceManager.GetString("VentProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall perimeter effect.
        /// </summary>
        public static string WallPerimeterEffect {
            get {
                return ResourceManager.GetString("WallPerimeterEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall Type.
        /// </summary>
        public static string WallType {
            get {
                return ResourceManager.GetString("WallType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By editing the window configuration you will lose your current calculation results and reports. Would you like to continue editing the configuration?.
        /// </summary>
        public static string WarningForDisableResult {
            get {
                return ResourceManager.GetString("WarningForDisableResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must apply a configuration for all glass panels..
        /// </summary>
        public static string WarningForGlassPanel {
            get {
                return ResourceManager.GetString("WarningForGlassPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured. Please refresh the page..
        /// </summary>
        public static string WarningForRefreshPage {
            get {
                return ResourceManager.GetString("WarningForRefreshPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splitting panes will remove panes you have added to your glass configurations. Do you want to continue?.
        /// </summary>
        public static string WarningForSplittingPanes {
            get {
                return ResourceManager.GetString("WarningForSplittingPanes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Back.
        /// </summary>
        public static string WelcomeBack {
            get {
                return ResourceManager.GetString("WelcomeBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind load.
        /// </summary>
        public static string WindLoad {
            get {
                return ResourceManager.GetString("WindLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows are to be shown in the building with floor &lt;br /&gt;
        ///dash-lines (representing elevations) and zone dash-lines &lt;br /&gt;
        ///(denoting window location zones)..
        /// </summary>
        public static string WindowDescription {
            get {
                return ResourceManager.GetString("WindowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Dimension.
        /// </summary>
        public static string WindowDimension {
            get {
                return ResourceManager.GetString("WindowDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window elevation.
        /// </summary>
        public static string WindowElevation {
            get {
                return ResourceManager.GetString("WindowElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window height.
        /// </summary>
        public static string WindowHeight {
            get {
                return ResourceManager.GetString("WindowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window information.
        /// </summary>
        public static string WindowInformation {
            get {
                return ResourceManager.GetString("WindowInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window width.
        /// </summary>
        public static string WindowWidth {
            get {
                return ResourceManager.GetString("WindowWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window zone.
        /// </summary>
        public static string WindowZone {
            get {
                return ResourceManager.GetString("WindowZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Pressure.
        /// </summary>
        public static string WindPressure {
            get {
                return ResourceManager.GetString("WindPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Speed.
        /// </summary>
        public static string WindSpeed {
            get {
                return ResourceManager.GetString("WindSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Zone.
        /// </summary>
        public static string WindZone {
            get {
                return ResourceManager.GetString("WindZone", resourceCulture);
            }
        }
    }
}
