//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCLWebAPI.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcousticReport
    {
        public long AcousticReportId { get; set; }
        public string FileName { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        public string ProductType { get; set; }
        public string OpeningType { get; set; }
        public string GlassLite1 { get; set; }
        public string GlassAirSpaceOne { get; set; }
        public string GlassLite2 { get; set; }
        public string GlassAirSpaceTwo { get; set; }
        public string GlassLite3 { get; set; }
        public Nullable<int> STC { get; set; }
        public Nullable<int> OITC { get; set; }
        public Nullable<int> Rw { get; set; }
        public Nullable<int> C { get; set; }
        public Nullable<int> Ctr { get; set; }
        public Nullable<decimal> TransmissionLoss50 { get; set; }
        public Nullable<decimal> TransmissionLoss63 { get; set; }
        public Nullable<decimal> TransmissionLoss80 { get; set; }
        public Nullable<decimal> TransmissionLoss100 { get; set; }
        public Nullable<decimal> TransmissionLoss125 { get; set; }
        public Nullable<decimal> TransmissionLoss160 { get; set; }
        public Nullable<decimal> TransmissionLoss200 { get; set; }
        public Nullable<decimal> TransmissionLoss250 { get; set; }
        public Nullable<decimal> TransmissionLoss315 { get; set; }
        public Nullable<decimal> TransmissionLoss400 { get; set; }
        public Nullable<decimal> TransmissionLoss500 { get; set; }
        public Nullable<decimal> TransmissionLoss630 { get; set; }
        public Nullable<decimal> TransmissionLoss800 { get; set; }
        public Nullable<decimal> TransmissionLoss1000 { get; set; }
        public Nullable<decimal> TransmissionLoss1250 { get; set; }
        public Nullable<decimal> TransmissionLoss1600 { get; set; }
        public Nullable<decimal> TransmissionLoss2000 { get; set; }
        public Nullable<decimal> TransmissionLoss2500 { get; set; }
        public Nullable<decimal> TransmissionLoss3150 { get; set; }
        public Nullable<decimal> TransmissionLoss4000 { get; set; }
        public Nullable<decimal> TransmissionLoss5000 { get; set; }
        public Nullable<decimal> TransmissionLoss6300 { get; set; }
        public Nullable<decimal> TransmissionLoss8000 { get; set; }
        public Nullable<decimal> TransmissionLoss10000 { get; set; }
    }
}
