//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCLWebAPI.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.CustomArticle = new HashSet<CustomArticle>();
            this.Product = new HashSet<Product>();
        }
    
        public int ArticleId { get; set; }
        public Nullable<System.Guid> ArticleGuid { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public int ArticleTypeId { get; set; }
        public string CrossSectionUrl { get; set; }
        public string Description { get; set; }
        public Nullable<double> InsideDimension { get; set; }
        public Nullable<double> OutsideDimension { get; set; }
        public Nullable<double> Dimension { get; set; }
        public string OffsetReference { get; set; }
        public Nullable<double> LeftRebate { get; set; }
        public Nullable<double> RightRebate { get; set; }
        public Nullable<double> DistBetweenIsoBars { get; set; }
        public Nullable<double> Depth { get; set; }
    
        public virtual ArticleType ArticleType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomArticle> CustomArticle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
    }
}
