//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCLWebAPI.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASEArticle
    {
        public int ArticleSetID { get; set; }
        public string ArticleName { get; set; }
        public string System { get; set; }
        public Nullable<int> SRS { get; set; }
        public string Category { get; set; }
        public string ProfileType { get; set; }
        public Nullable<double> InsideW { get; set; }
        public Nullable<double> OutsideW { get; set; }
        public Nullable<double> Depth { get; set; }
        public string IsolatorType { get; set; }
        public Nullable<double> ExtrusionLength { get; set; }
    }
}
