//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCLWebAPI.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoorHandleHinge
    {
        public int ArticleSetID { get; set; }
        public string ArticleName { get; set; }
        public string Color { get; set; }
        public string Color_Code { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
    }
}
