//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCLWebAPI.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacadeArticle
    {
        public int ArticleSetID { get; set; }
        public string System { get; set; }
        public string Mullion { get; set; }
        public Nullable<int> Mullion_Depth { get; set; }
        public string Mullion_Reinforcement_Type1 { get; set; }
        public string Mullion_Reinforcement_Type1_Material { get; set; }
        public string Mullion_Reinforcement_Type2 { get; set; }
        public string Mullion_Reinforcement_Type2_Material { get; set; }
        public string Transom { get; set; }
        public Nullable<int> Transom_Depth { get; set; }
        public string Level_2_Transom { get; set; }
        public Nullable<int> Level_2_Transom_Depth { get; set; }
        public string Transom_Reinforcement { get; set; }
        public string Transom_Reinforcement_Material { get; set; }
    }
}
