//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCLWebAPI.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacadeSpacer1
    {
        public int FacadeSpacerId { get; set; }
        public Nullable<System.Guid> FacadeSpacerGuid { get; set; }
        public string System { get; set; }
        public string InsulationZone { get; set; }
        public int GlazingLayer { get; set; }
        public int Depth { get; set; }
        public double FacadeSpacer_1 { get; set; }
        public double FacadeSpacer_2 { get; set; }
        public double FacadeSpacer_3 { get; set; }
        public double FacadeSpacer_83 { get; set; }
        public double FacadeSpacer_51 { get; set; }
        public double FacadeSpacer_22 { get; set; }
        public double FacadeSpacer_31 { get; set; }
        public double FacadeSpacer_71 { get; set; }
        public double FacadeSpacer_52 { get; set; }
        public double FacadeSpacer_85 { get; set; }
        public double FacadeSpacer_92 { get; set; }
        public double FacadeSpacer_101 { get; set; }
        public double FacadeSpacer_93 { get; set; }
        public double FacadeSpacer_21 { get; set; }
        public double FacadeSpacer_111 { get; set; }
        public double FacadeSpacer_61 { get; set; }
        public double FacadeSpacer_72 { get; set; }
        public double FacadeSpacer_81 { get; set; }
        public double FacadeSpacer_84 { get; set; }
        public double FacadeSpacer_11 { get; set; }
        public double FacadeSpacer_91 { get; set; }
        public double FacadeSpacer_23 { get; set; }
        public double FacadeSpacer_41 { get; set; }
        public double FacadeSpacer_82 { get; set; }
    }
}
