//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCLWebAPI.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlassSRS1
    {
        public int GlassTypeID { get; set; }
        public string GlassType { get; set; }
        public string Composition { get; set; }
        public string Type { get; set; }
        public Nullable<double> Total_Thickness { get; set; }
        public Nullable<double> U_value { get; set; }
        public Nullable<int> Rw { get; set; }
        public Nullable<int> Spacer { get; set; }
        public Nullable<double> shgc { get; set; }
        public Nullable<double> vt { get; set; }
        public Nullable<int> rwc { get; set; }
        public Nullable<int> rwctr { get; set; }
        public Nullable<int> stc { get; set; }
        public Nullable<int> oitc { get; set; }
    }
}
