//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCLWebAPI.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsulatingBar1
    {
        public int InsulatingBarId { get; set; }
        public Nullable<System.Guid> InsulatingBarGuid { get; set; }
        public int ArticleId { get; set; }
        public string ProductName { get; set; }
        public string PTCoatedBefore { get; set; }
        public string PTAnodizedBefore { get; set; }
        public string PACoatedBefore { get; set; }
        public string PACoatedAfter { get; set; }
        public string PAAnodizedBefore { get; set; }
        public string PAAnodizedAfter { get; set; }
    }
}
