//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCLWebAPI.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThermalBtoBBlockData
    {
        public int BlockID { get; set; }
        public string Series { get; set; }
        public double VentFWidth { get; set; }
        public string FixedorOperable { get; set; }
        public double GlassThickness { get; set; }
        public string PAPT { get; set; }
        public double k { get; set; }
        public double I { get; set; }
    }
}
