//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCLWebAPI.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class UDCArticle1
    {
        public int ArticleSetID { get; set; }
        public string ArticleName { get; set; }
        public string Type { get; set; }
        public Nullable<int> AB { get; set; }
        public Nullable<int> BT { get; set; }
        public string BottomFraming { get; set; }
    }
}
