//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCLWebAPI.Models.Edmx
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using VCLWebAPI.Configurations;
    using VCLWebAPI.Utils;

    [DbConfigurationType(typeof(VCLDesignDBConfiguration))]
    public partial class VCLDesignDBEntities : DbContext
    {
        public VCLDesignDBEntities()
            : base(Globals.ConnectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessRole> AccessRole { get; set; }
        public virtual DbSet<AcousticReport> AcousticReport { get; set; }
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<ADSArticle> ADSArticle { get; set; }
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<ArticleSectionalProperty> ArticleSectionalProperty { get; set; }
        public virtual DbSet<ArticleType> ArticleType { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<BpsBoundaryCondition> BpsBoundaryCondition { get; set; }
        public virtual DbSet<BpsProblem> BpsProblem { get; set; }
        public virtual DbSet<BpsProject> BpsProject { get; set; }
        public virtual DbSet<BpsUnifiedProblem> BpsUnifiedProblem { get; set; }
        public virtual DbSet<CustomArticle> CustomArticle { get; set; }
        public virtual DbSet<Dealer> Dealer { get; set; }
        public virtual DbSet<DoorHandleHinge> DoorHandleHinge { get; set; }
        public virtual DbSet<ExternalClient> ExternalClient { get; set; }
        public virtual DbSet<Fabricator> Fabricator { get; set; }
        public virtual DbSet<FacadeArticle> FacadeArticle { get; set; }
        public virtual DbSet<FacadeArticleSectionalProperty> FacadeArticleSectionalProperty { get; set; }
        public virtual DbSet<FacadeInsertUnit> FacadeInsertUnit { get; set; }
        public virtual DbSet<FacadeProfile> FacadeProfile { get; set; }
        public virtual DbSet<FacadeSpacer> FacadeSpacer { get; set; }
        public virtual DbSet<Feature> Feature { get; set; }
        public virtual DbSet<Financial> Financial { get; set; }
        public virtual DbSet<GlassBPS> GlassBPS { get; set; }
        public virtual DbSet<GlassSRS> GlassSRS { get; set; }
        public virtual DbSet<InsulatingBar> InsulatingBar { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Order_Status> Order_Status { get; set; }
        public virtual DbSet<OrderDetails> OrderDetails { get; set; }
        public virtual DbSet<Permission> Permission { get; set; }
        public virtual DbSet<Permission_Role> Permission_Role { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductType> ProductType { get; set; }
        public virtual DbSet<SLU_Status> SLU_Status { get; set; }
        public virtual DbSet<StateTax> StateTax { get; set; }
        public virtual DbSet<ThermalBtoBBlockData> ThermalBtoBBlockData { get; set; }
        public virtual DbSet<ThermalBtoBDirectData> ThermalBtoBDirectData { get; set; }
        public virtual DbSet<ThermalBtoBStandardData> ThermalBtoBStandardData { get; set; }
        public virtual DbSet<UDCArticle> UDCArticle { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<WindZoneGermany> WindZoneGermany { get; set; }
        public virtual DbSet<ASEArticle> ASEArticle { get; set; }
    }
}
