//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCLWebAPI.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleSectionalProperty
    {
        public string ArticleName { get; set; }
        public double InsideW { get; set; }
        public double OutsideW { get; set; }
        public double LeftRebate { get; set; }
        public double RightRebate { get; set; }
        public double DistBetweenIsoBars { get; set; }
        public double d { get; set; }
        public double Weight { get; set; }
        public double Ao { get; set; }
        public double Au { get; set; }
        public double Io { get; set; }
        public double Iu { get; set; }
        public double Ioyy { get; set; }
        public double Iuyy { get; set; }
        public double Zoo { get; set; }
        public double Zou { get; set; }
        public double Zol { get; set; }
        public double Zor { get; set; }
        public double Zuo { get; set; }
        public double Zuu { get; set; }
        public double Zul { get; set; }
        public double Zur { get; set; }
        public double RSn20 { get; set; }
        public double RSp80 { get; set; }
        public double RTn20 { get; set; }
        public double RTp80 { get; set; }
        public double Cn20 { get; set; }
        public double Cp20 { get; set; }
        public double Cp80 { get; set; }
        public double beta { get; set; }
        public double A2 { get; set; }
        public double E { get; set; }
        public double alpha { get; set; }
        public double Woyp { get; set; }
        public double Woyn { get; set; }
        public double Wozp { get; set; }
        public double Wozn { get; set; }
        public double Wuyp { get; set; }
        public double Wuyn { get; set; }
        public double Wuzp { get; set; }
        public double Wuzn { get; set; }
        public double Depth { get; set; }
    }
}
