//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCLWebAPI.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomArticle1
    {
        public int CustomArticleId { get; set; }
        public Nullable<System.Guid> CustomArticleGuid { get; set; }
        public int ArticleId { get; set; }
        public string Category { get; set; }
        public string Spacer { get; set; }
        public string Element_level_1 { get; set; }
        public string Element_type_1 { get; set; }
        public string Element_size_1 { get; set; }
        public string Element_interlayer_1 { get; set; }
        public string Element_lam_type_1 { get; set; }
        public string Element_lam_size_1 { get; set; }
        public string Element_level_2 { get; set; }
        public string Element_type_2 { get; set; }
        public string Element_size_2 { get; set; }
        public string Element_interlayer_2 { get; set; }
        public string Element_lam_type_2 { get; set; }
        public string Element_lam_size_2 { get; set; }
        public string Element_level_3 { get; set; }
        public string Element_type_3 { get; set; }
        public string Element_size_3 { get; set; }
        public string Element_interlayer_3 { get; set; }
        public string UValue { get; set; }
        public string GlassRW { get; set; }
    
        public virtual Article1 Article { get; set; }
    }
}
