//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCLWebAPI.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dealer1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dealer1()
        {
            this.Financial = new HashSet<Financial1>();
            this.Order = new HashSet<Order1>();
            this.User = new HashSet<User1>();
        }
    
        public int DealerId { get; set; }
        public System.Guid DealerExternalId { get; set; }
        public string Name { get; set; }
        public string PrimaryContactName { get; set; }
        public Nullable<int> AddressId { get; set; }
        public string PrimaryContactEmail { get; set; }
        public string PrimaryContactPhone { get; set; }
        public double CreditLine { get; set; }
        public Nullable<double> DefaultSalesTaxRate { get; set; }
        public int AWSFabricatorId { get; set; }
        public int ADSFabricatorId { get; set; }
        public int ASSFabricatorId { get; set; }
    
        public virtual Address1 Address { get; set; }
        public virtual Fabricator1 Fabricator { get; set; }
        public virtual Fabricator1 Fabricator1 { get; set; }
        public virtual Fabricator1 Fabricator2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Financial1> Financial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order1> Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User1> User { get; set; }
    }
}
