//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCLWebAPI.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dealer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dealer()
        {
            this.Financial = new HashSet<Financial>();
            this.Order = new HashSet<Order>();
            this.User = new HashSet<User>();
        }
    
        public int DealerId { get; set; }
        public System.Guid DealerExternalId { get; set; }
        public string Name { get; set; }
        public string PrimaryContactName { get; set; }
        public Nullable<int> AddressId { get; set; }
        public string PrimaryContactEmail { get; set; }
        public string PrimaryContactPhone { get; set; }
        public double CreditLine { get; set; }
        public Nullable<double> DefaultSalesTaxRate { get; set; }
        public int AWSFabricatorId { get; set; }
        public int ADSFabricatorId { get; set; }
        public int ASSFabricatorId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Fabricator Fabricator { get; set; }
        public virtual Fabricator Fabricator1 { get; set; }
        public virtual Fabricator Fabricator2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Financial> Financial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
    }
}
