//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCLWebAPI.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacadeInsertUnit1
    {
        public int FacadeInsertUnitId { get; set; }
        public Nullable<System.Guid> FacadeInsertUnitGuid { get; set; }
        public string System { get; set; }
        public string OpeningType { get; set; }
        public string Material { get; set; }
        public int GlassThicknessMin { get; set; }
        public int GlassThicknessMax { get; set; }
        public double Uf { get; set; }
    }
}
