//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCLWebAPI.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacadeProfile
    {
        public int FacadeProfileId { get; set; }
        public Nullable<System.Guid> FacadeProfileGuid { get; set; }
        public string System { get; set; }
        public string InsulationZone { get; set; }
        public string ProfileType { get; set; }
        public int GlassThicknessMin { get; set; }
        public int GlassThicknessMax { get; set; }
        public double FacadeProfileTable_k { get; set; }
        public double FacadeProfileTable_l { get; set; }
    }
}
