//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCLWebAPI.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacadeArticleSectionalProperty1
    {
        public string ArticleName { get; set; }
        public double OutsideW { get; set; }
        public double BTDepth { get; set; }
        public double Width { get; set; }
        public double Zo { get; set; }
        public double Zu { get; set; }
        public double Zl { get; set; }
        public double Zr { get; set; }
        public double A { get; set; }
        public string Material { get; set; }
        public double beta { get; set; }
        public double Weight { get; set; }
        public double Iyy { get; set; }
        public double Izz { get; set; }
        public double Wyy { get; set; }
        public double Wzz { get; set; }
        public double Asy { get; set; }
        public double Asz { get; set; }
        public double J { get; set; }
        public double E { get; set; }
        public double G { get; set; }
        public double EA { get; set; }
        public double GAsy { get; set; }
        public double GAsz { get; set; }
        public double EIy { get; set; }
        public double EIz { get; set; }
        public double GJ { get; set; }
        public double Ys { get; set; }
        public double Zs { get; set; }
        public double Ry { get; set; }
        public double Rz { get; set; }
        public double Wyp { get; set; }
        public double Wyn { get; set; }
        public double Wzp { get; set; }
        public double Wzn { get; set; }
        public double Cw { get; set; }
        public double Beta_torsion { get; set; }
        public double Zy { get; set; }
        public double Zz { get; set; }
        public double Depth { get; set; }
    }
}
