//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCLWebAPI.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Financial1
    {
        public int FinancialId { get; set; }
        public System.Guid FinancialExternalId { get; set; }
        public int DealerId { get; set; }
        public double LineOfCredit { get; set; }
        public double OrdersToDate { get; set; }
        public double PaidToDate { get; set; }
        public double CurrentBalance { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual Dealer1 Dealer { get; set; }
        public virtual User1 User { get; set; }
        public virtual User1 User1 { get; set; }
    }
}
