//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCLWebAPI.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public int OrderDetailId { get; set; }
        public System.Guid OrderDetailExternalId { get; set; }
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public string DesignURL { get; set; }
        public string JsonURL { get; set; }
        public string ProposalURL { get; set; }
        public string BomURL { get; set; }
        public string OrderDetailscol { get; set; }
        public string UnitPrice { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> SubTotal { get; set; }
        public string AdditionalDetails { get; set; }
    
        public virtual BpsUnifiedProblem BpsUnifiedProblem { get; set; }
        public virtual Order Order { get; set; }
    }
}
