//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCLWebAPI.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThermalBtoBDirectData1
    {
        public int DirectID { get; set; }
        public string Series { get; set; }
        public string GlazingInsulationType { get; set; }
        public string FixedorOperable { get; set; }
        public double GlassThickness { get; set; }
        public string PAPT { get; set; }
        public double C382180 { get; set; }
        public double C382200 { get; set; }
        public double C382310 { get; set; }
        public double C382330 { get; set; }
        public double C382340 { get; set; }
        public double C382110 { get; set; }
        public double C382170 { get; set; }
        public double C374980 { get; set; }
    }
}
