USE `vcldesigndb`;

ALTER TABLE `aspnetusers` 
ADD COLUMN `NormalizedEmail` VARCHAR(256) NULL DEFAULT NULL,
ADD COLUMN `NormalizedUserName` VARCHAR(256) NULL DEFAULT NULL,
ADD COLUMN `ConcurrencyStamp` LONGTEXT NULL DEFAULT NULL,
ADD COLUMN `LockoutEnd` DATETIME NULL DEFAULT NULL;